apiVersion: apps/v1
kind: Deployment
metadata:
  name:  myapp
  labels:
    app:  myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app:  myapp
      ### Use this block 
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'myapp-homolog' #secret access role
        vault.hashicorp.com/auth-path: 'auth/dev-cluster' # auth method path (default auth/kubernetes)
        vault.hashicorp.com/agent-inject-secret-config: 'dev-cluster/data/homolog/myapp/config' #secret path
        vault.hashicorp.com/agent-inject-template-config: | #format secret using key=value format
          {{ with secret "dev-cluster/data/homolog/myapp/config" -}}
          {{ range $k, $v := .Data.data }}
          {{ $k }}={{ $v }}
          {{ end }}
          {{- end }}
      ###    
    spec:
      serviceAccountName: myapp-sa # use an service account according to your role
      containers:
      - name:  myapp
        image:  alpine:latest
        imagePullPolicy: IfNotPresent
        command: ['sh']
        args:
        - '-c'
        - 'export $(/bin/cat /vault/secrets/config) && env && sleep 1000' # load envs from secret destination file
---
# This service account are allowed to access secret (this is defined by myapp role)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp-sa